/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountParticipation } from './account-participation';
import { Application } from './application';
import { ApplicationLocalState } from './application-local-state';
import { ApplicationStateSchema } from './application-state-schema';
import { Asset } from './asset';
import { AssetHolding } from './asset-holding';
/**
 * Account information at a given round.  Definition: data/basics/userBalance.go : AccountData 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {AccountParticipation}
     * @memberof Account
     */
    participation?: AccountParticipation;
    /**
     * \\[tbx\\] The number of existing boxes created by this account's app.
     * @type {number}
     * @memberof Account
     */
    totalBoxes?: number;
    /**
     * \\[algo\\] total number of MicroAlgos in the account
     * @type {number}
     * @memberof Account
     */
    amount: number;
    /**
     * the account public key
     * @type {string}
     * @memberof Account
     */
    address: string;
    /**
     * MicroAlgo balance required by the account. The requirement grows based on asset and application usage.
     * @type {number}
     * @memberof Account
     */
    minBalance: number;
    /**
     * \\[appl\\] applications local data stored in this account.  Note the raw object uses `map[int] -> AppLocalState` for this type.
     * @type {Array<ApplicationLocalState>}
     * @memberof Account
     */
    appsLocalState?: Array<ApplicationLocalState>;
    /**
     * \\[apar\\] parameters of assets created by this account.  Note: the raw account uses `map[int] -> Asset` for this type.
     * @type {Array<Asset>}
     * @memberof Account
     */
    createdAssets?: Array<Asset>;
    /**
     * 
     * @type {ApplicationStateSchema}
     * @memberof Account
     */
    appsTotalSchema?: ApplicationStateSchema;
    /**
     * \\[ebase\\] used as part of the rewards computation. Only applicable to accounts which are participating.
     * @type {number}
     * @memberof Account
     */
    rewardBase?: number;
    /**
     * amount of MicroAlgos of pending rewards in this account.
     * @type {number}
     * @memberof Account
     */
    pendingRewards: number;
    /**
     * \\[appp\\] parameters of applications created by this account including app global data.  Note: the raw account uses `map[int] -> AppParams` for this type.
     * @type {Array<Application>}
     * @memberof Account
     */
    createdApps?: Array<Application>;
    /**
     * The count of all assets that have been opted in, equivalent to the count of AssetHolding objects held by this account.
     * @type {number}
     * @memberof Account
     */
    totalAssetsOptedIn: number;
    /**
     * The count of all applications that have been opted in, equivalent to the count of application local data (AppLocalState objects) stored in this account.
     * @type {number}
     * @memberof Account
     */
    totalAppsOptedIn: number;
    /**
     * \\[tbxb\\] The total number of bytes used by this account's app's box keys and values.
     * @type {number}
     * @memberof Account
     */
    totalBoxBytes?: number;
    /**
     * The count of all apps (AppParams objects) created by this account.
     * @type {number}
     * @memberof Account
     */
    totalCreatedApps: number;
    /**
     * \\[asset\\] assets held by this account.  Note the raw object uses `map[int] -> AssetHolding` for this type.
     * @type {Array<AssetHolding>}
     * @memberof Account
     */
    assets?: Array<AssetHolding>;
    /**
     * \\[teap\\] the sum of all extra application program pages for this account.
     * @type {number}
     * @memberof Account
     */
    appsTotalExtraPages?: number;
    /**
     * The round for which this information is relevant.
     * @type {number}
     * @memberof Account
     */
    round: number;
    /**
     * The count of all assets (AssetParams objects) created by this account.
     * @type {number}
     * @memberof Account
     */
    totalCreatedAssets: number;
    /**
     * specifies the amount of MicroAlgos in the account, without the pending rewards.
     * @type {number}
     * @memberof Account
     */
    amountWithoutPendingRewards: number;
    /**
     * \\[spend\\] the address against which signing should be checked. If empty, the address of the current account is used. This field can be updated in any transaction by setting the RekeyTo field.
     * @type {string}
     * @memberof Account
     */
    authAddr?: string;
    /**
     * \\[ern\\] total rewards of MicroAlgos the account has received, including pending rewards.
     * @type {number}
     * @memberof Account
     */
    rewards: number;
    /**
     * \\[onl\\] delegation status of the account's MicroAlgos * Offline - indicates that the associated account is delegated. *  Online  - indicates that the associated account used as part of the delegation pool. *   NotParticipating - indicates that the associated account is neither a delegator nor a delegate.
     * @type {string}
     * @memberof Account
     */
    status: string;
    /**
     * Indicates what type of signature is used by this account, must be one of: * sig * msig * lsig
     * @type {string}
     * @memberof Account
     */
    sigType?: AccountSigTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum AccountSigTypeEnum {
    Sig = 'sig',
    Msig = 'msig',
    Lsig = 'lsig'
}

