/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationLocalState } from './application-local-state';
import { ApplicationParams } from './application-params';
/**
 * AccountApplicationResponse describes the account's application local state and global state (AppLocalState and AppParams, if either exists) for a specific application ID. Global state will only be returned if the provided address is the application's creator.
 * @export
 * @interface AccountApplicationResponse
 */
export interface AccountApplicationResponse {
    /**
     * The round for which this information is relevant.
     * @type {number}
     * @memberof AccountApplicationResponse
     */
    round: number;
    /**
     * 
     * @type {ApplicationParams}
     * @memberof AccountApplicationResponse
     */
    createdApp?: ApplicationParams;
    /**
     * 
     * @type {ApplicationLocalState}
     * @memberof AccountApplicationResponse
     */
    appLocalState?: ApplicationLocalState;
}
