/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * AccountParticipation describes the parameters used by this account in consensus protocol.
 * @export
 * @interface AccountParticipation
 */
export interface AccountParticipation {
    /**
     * \\[stprf\\] Root of the state proof key (if any)
     * @type {string}
     * @memberof AccountParticipation
     */
    stateProofKey?: string;
    /**
     * \\[vote\\] root participation public key (if any) currently registered for this round.
     * @type {string}
     * @memberof AccountParticipation
     */
    voteParticipationKey: string;
    /**
     * \\[voteLst\\] Last round for which this participation is valid.
     * @type {number}
     * @memberof AccountParticipation
     */
    voteLastValid: number;
    /**
     * \\[voteKD\\] Number of subkeys in each batch of participation keys.
     * @type {number}
     * @memberof AccountParticipation
     */
    voteKeyDilution: number;
    /**
     * \\[voteFst\\] First round for which this participation is valid.
     * @type {number}
     * @memberof AccountParticipation
     */
    voteFirstValid: number;
    /**
     * \\[sel\\] Selection public key (if any) currently registered for this round.
     * @type {string}
     * @memberof AccountParticipation
     */
    selectionParticipationKey: string;
}
