/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssetHolding } from './asset-holding';
import { AssetParams } from './asset-params';
/**
 * AccountAssetResponse describes the account's asset holding and asset parameters (if either exist) for a specific asset ID. Asset parameters will only be returned if the provided address is the asset's creator.
 * @export
 * @interface AccountAssetResponse
 */
export interface AccountAssetResponse {
    /**
     * 
     * @type {AssetHolding}
     * @memberof AccountAssetResponse
     */
    assetHolding?: AssetHolding;
    /**
     * The round for which this information is relevant.
     * @type {number}
     * @memberof AccountAssetResponse
     */
    round: number;
    /**
     * 
     * @type {AssetParams}
     * @memberof AccountAssetResponse
     */
    createdAsset?: AssetParams;
}
