/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationStateSchema } from './application-state-schema';
import { TealKeyValueStore } from './teal-key-value-store';
/**
 * Stores the global information associated with an application.
 * @export
 * @interface ApplicationParams
 */
export interface ApplicationParams {
    /**
     * 
     * @type {TealKeyValueStore}
     * @memberof ApplicationParams
     */
    globalState?: TealKeyValueStore;
    /**
     * \\[clearp\\] approval program.
     * @type {string}
     * @memberof ApplicationParams
     */
    clearStateProgram: string;
    /**
     * The address that created this application. This is the address where the parameters and global state for this application can be found.
     * @type {string}
     * @memberof ApplicationParams
     */
    creator: string;
    /**
     * 
     * @type {ApplicationStateSchema}
     * @memberof ApplicationParams
     */
    localStateSchema?: ApplicationStateSchema;
    /**
     * \\[approv\\] approval program.
     * @type {string}
     * @memberof ApplicationParams
     */
    approvalProgram: string;
    /**
     * \\[epp\\] the amount of extra program pages available to this app.
     * @type {number}
     * @memberof ApplicationParams
     */
    extraProgramPages?: number;
    /**
     * 
     * @type {ApplicationStateSchema}
     * @memberof ApplicationParams
     */
    globalStateSchema?: ApplicationStateSchema;
}
