/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationStateSchema } from './application-state-schema';
import { TealKeyValueStore } from './teal-key-value-store';
/**
 * Stores local state associated with an application.
 * @export
 * @interface ApplicationLocalState
 */
export interface ApplicationLocalState {
    /**
     * 
     * @type {ApplicationStateSchema}
     * @memberof ApplicationLocalState
     */
    schema: ApplicationStateSchema;
    /**
     * 
     * @type {TealKeyValueStore}
     * @memberof ApplicationLocalState
     */
    keyValue?: TealKeyValueStore;
    /**
     * The application which this local state is for.
     * @type {number}
     * @memberof ApplicationLocalState
     */
    id: number;
}
