/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Describes an asset held by an account.  Definition: data/basics/userBalance.go : AssetHolding
 * @export
 * @interface AssetHolding
 */
export interface AssetHolding {
    /**
     * \\[a\\] number of units held.
     * @type {number}
     * @memberof AssetHolding
     */
    amount: number;
    /**
     * Asset ID of the holding.
     * @type {number}
     * @memberof AssetHolding
     */
    assetId: number;
    /**
     * \\[f\\] whether or not the holding is frozen.
     * @type {boolean}
     * @memberof AssetHolding
     */
    isFrozen: boolean;
}
