/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssetParams } from './asset-params';
/**
 * Specifies both the unique identifier and the parameters for an asset
 * @export
 * @interface Asset
 */
export interface Asset {
    /**
     * unique asset identifier
     * @type {number}
     * @memberof Asset
     */
    index: number;
    /**
     * 
     * @type {AssetParams}
     * @memberof Asset
     */
    params: AssetParams;
}
