/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Block } from './block';
/**
 * Encoded block object.
 * @export
 * @interface BlockResponse
 */
export interface BlockResponse {
    /**
     * Optional certificate object. This is only included when the format is set to message pack.
     * @type {any}
     * @memberof BlockResponse
     */
    cert?: any;
    /**
     * 
     * @type {Block}
     * @memberof BlockResponse
     */
    block: Block;
}
