/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CompileResponse
 */
export interface CompileResponse {
    /**
     * base64 encoded program bytes
     * @type {string}
     * @memberof CompileResponse
     */
    result: string;
    /**
     * JSON of the source map
     * @type {any}
     * @memberof CompileResponse
     */
    sourcemap?: any;
    /**
     * base32 SHA512_256 of program bytes (Address style)
     * @type {string}
     * @memberof CompileResponse
     */
    hash: string;
}
