/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TealValue } from './teal-value';
/**
 * Stores the TEAL eval step data
 * @export
 * @interface DryrunState
 */
export interface DryrunState {
    /**
     * 
     * @type {Array<TealValue>}
     * @memberof DryrunState
     */
    stack: Array<TealValue>;
    /**
     * Program counter
     * @type {number}
     * @memberof DryrunState
     */
    pc: number;
    /**
     * Line number
     * @type {number}
     * @memberof DryrunState
     */
    line: number;
    /**
     * 
     * @type {Array<TealValue>}
     * @memberof DryrunState
     */
    scratch?: Array<TealValue>;
    /**
     * Evaluation error if any
     * @type {string}
     * @memberof DryrunState
     */
    error?: string;
}
