/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DryrunTxnResult } from './dryrun-txn-result';
/**
 * DryrunResponse contains per-txn debug information from a dryrun.
 * @export
 * @interface DryrunResponse
 */
export interface DryrunResponse {
    /**
     * Protocol version is the protocol version Dryrun was operated under.
     * @type {string}
     * @memberof DryrunResponse
     */
    protocolVersion: string;
    /**
     * 
     * @type {string}
     * @memberof DryrunResponse
     */
    error: string;
    /**
     * 
     * @type {Array<DryrunTxnResult>}
     * @memberof DryrunResponse
     */
    txns: Array<DryrunTxnResult>;
}
