/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * DryrunSource is TEAL source text that gets uploaded, compiled, and inserted into transactions or application state.
 * @export
 * @interface DryrunSource
 */
export interface DryrunSource {
    /**
     * FieldName is what kind of sources this is. If lsig then it goes into the transactions[this.TxnIndex].LogicSig. If approv or clearp it goes into the Approval Program or Clear State Program of application[this.AppIndex].
     * @type {string}
     * @memberof DryrunSource
     */
    fieldName: string;
    /**
     * 
     * @type {number}
     * @memberof DryrunSource
     */
    appIndex: number;
    /**
     * 
     * @type {string}
     * @memberof DryrunSource
     */
    source: string;
    /**
     * 
     * @type {number}
     * @memberof DryrunSource
     */
    txnIndex: number;
}
