/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Proof of membership and position of a light block header.
 * @export
 * @interface LightBlockHeaderProof
 */
export interface LightBlockHeaderProof {
    /**
     * Represents the depth of the tree that is being proven, i.e. the number of edges from a leaf to the root.
     * @type {number}
     * @memberof LightBlockHeaderProof
     */
    treedepth: number;
    /**
     * The index of the light block header in the vector commitment tree
     * @type {number}
     * @memberof LightBlockHeaderProof
     */
    index: number;
    /**
     * The encoded proof.
     * @type {string}
     * @memberof LightBlockHeaderProof
     */
    proof: string;
}
