/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountStateDelta } from './account-state-delta';
import { PendingTransactionResponse } from './pending-transaction-response';
import { StateDelta } from './state-delta';
/**
 * Details about a pending transaction. If the transaction was recently confirmed, includes confirmation details like the round and reward details.
 * @export
 * @interface PendingTransactionResponse
 */
export interface PendingTransactionResponse {
    /**
     * Rewards in microalgos applied to the receiver account.
     * @type {number}
     * @memberof PendingTransactionResponse
     */
    receiverRewards?: number;
    /**
     * The asset index if the transaction was found and it created an asset.
     * @type {number}
     * @memberof PendingTransactionResponse
     */
    assetIndex?: number;
    /**
     * The round where this transaction was confirmed, if present.
     * @type {number}
     * @memberof PendingTransactionResponse
     */
    confirmedRound?: number;
    /**
     * Indicates that the transaction was kicked out of this node's transaction pool (and specifies why that happened).  An empty string indicates the transaction wasn't kicked out of this node's txpool due to an error. 
     * @type {string}
     * @memberof PendingTransactionResponse
     */
    poolError: string;
    /**
     * The raw signed transaction.
     * @type {any}
     * @memberof PendingTransactionResponse
     */
    txn: any;
    /**
     * Rewards in microalgos applied to the sender account.
     * @type {number}
     * @memberof PendingTransactionResponse
     */
    senderRewards?: number;
    /**
     * \\[ld\\] Local state key/value changes for the application being executed by this transaction.
     * @type {Array<AccountStateDelta>}
     * @memberof PendingTransactionResponse
     */
    localStateDelta?: Array<AccountStateDelta>;
    /**
     * The application index if the transaction was found and it created an application.
     * @type {number}
     * @memberof PendingTransactionResponse
     */
    applicationIndex?: number;
    /**
     * Closing amount for the transaction.
     * @type {number}
     * @memberof PendingTransactionResponse
     */
    closingAmount?: number;
    /**
     * Inner transactions produced by application execution.
     * @type {Array<PendingTransactionResponse>}
     * @memberof PendingTransactionResponse
     */
    innerTxns?: Array<PendingTransactionResponse>;
    /**
     * The number of the asset's unit that were transferred to the close-to address.
     * @type {number}
     * @memberof PendingTransactionResponse
     */
    assetClosingAmount?: number;
    /**
     * Rewards in microalgos applied to the close remainder to account.
     * @type {number}
     * @memberof PendingTransactionResponse
     */
    closeRewards?: number;
    /**
     * \\[lg\\] Logs for the application being executed by this transaction.
     * @type {Array<string>}
     * @memberof PendingTransactionResponse
     */
    logs?: Array<string>;
    /**
     * 
     * @type {StateDelta}
     * @memberof PendingTransactionResponse
     */
    globalStateDelta?: StateDelta;
}
