/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PendingTransactions is an array of signed transactions exactly as they were submitted.
 * @export
 * @interface PendingTransactionsResponse
 */
export interface PendingTransactionsResponse {
    /**
     * An array of signed transaction objects.
     * @type {Array<any>}
     * @memberof PendingTransactionsResponse
     */
    topTransactions: Array<any>;
    /**
     * Total number of transactions in the pool.
     * @type {number}
     * @memberof PendingTransactionsResponse
     */
    totalTransactions: number;
}
