/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Represents a TEAL value.
 * @export
 * @interface TealValue
 */
export interface TealValue {
    /**
     * \\[tb\\] bytes value.
     * @type {string}
     * @memberof TealValue
     */
    bytes: string;
    /**
     * \\[tt\\] value type. Value `1` refers to **bytes**, value `2` refers to **uint**
     * @type {number}
     * @memberof TealValue
     */
    type: number;
    /**
     * \\[ui\\] uint value.
     * @type {number}
     * @memberof TealValue
     */
    uint: number;
}
