/* tslint:disable */
/* eslint-disable */
/**
 * Algod Testnet V3 API v2
 * V2 API endpoint for algod operations.
 *
 * OpenAPI spec version: 3.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * TransactionParams contains the parameters that help a client construct a new transaction.
 * @export
 * @interface TransactionsParametersResponse
 */
export interface TransactionsParametersResponse {
    /**
     * GenesisHash is the hash of the genesis block.
     * @type {string}
     * @memberof TransactionsParametersResponse
     */
    genesisHash: string;
    /**
     * The minimum transaction fee (not per byte) required for the txn to validate for the current network protocol.
     * @type {number}
     * @memberof TransactionsParametersResponse
     */
    minFee: number;
    /**
     * ConsensusVersion indicates the consensus protocol version as of LastRound.
     * @type {string}
     * @memberof TransactionsParametersResponse
     */
    consensusVersion: string;
    /**
     * Fee is the suggested transaction fee Fee is in units of micro-Algos per byte. Fee may fall to zero but transactions must still have a fee of at least MinTxnFee for the current network protocol.
     * @type {number}
     * @memberof TransactionsParametersResponse
     */
    fee: number;
    /**
     * GenesisID is an ID listed in the genesis block.
     * @type {string}
     * @memberof TransactionsParametersResponse
     */
    genesisId: string;
    /**
     * LastRound indicates the last round seen
     * @type {number}
     * @memberof TransactionsParametersResponse
     */
    lastRound: number;
}
